### ISSUE TITLE
Confusing highlight in terminal mode

### ISSUE THREAD

**Issue by onsails** [Th3Whit3Wolf/one-nvim#1]
Thank you for the nice theme! I really enjoy it and [submitted it to nixpkgs](https://github.com/NixOS/nixpkgs/pull/110818).
I've spotted weird colors in terminal mode. I am using [vim-floaterm](https://github.com/voldikss/vim-floaterm) with zsh shell and [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) plugin.
Despite overall syntax highlighting this plugin highlights wrong binaries with red, good ones with green:
<img width="119" alt="image" src="https://user-images.githubusercontent.com/107261/105764760-7343e900-5f68-11eb-828d-aaa73a6c9db4.png">
<img width="77" alt="image" src="https://user-images.githubusercontent.com/107261/105764840-91114e00-5f68-11eb-9d58-d0ded61e6158.png">

But in neovim with one-nvim colorscheme it suddenly highlights right paths with red, bad paths with grey:
<img width="88" alt="image" src="https://user-images.githubusercontent.com/107261/105764896-a5ede180-5f68-11eb-926c-ca3d1451da6b.png">
<img width="46" alt="image" src="https://user-images.githubusercontent.com/107261/105764910-ab4b2c00-5f68-11eb-81a9-e7598fb85a2f.png">

Also, paths in git status  are barely visible:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/107261/105764978-c3bb4680-5f68-11eb-80c3-e96d535aa411.png">

**Comment by Th3Whit3Wolf** [comment]
Thank you for submitting this issue. This should be fixed now. Try updating and let me know if it persists.

**Comment by onsails** [comment]
Now it's perfect!
