### ISSUE TITLE
attempt to index field 'go' (a nil value)

### ISSUE THREAD

**Issue by pianocomposer321** [Th3Whit3Wolf/one-nvim#14]
After updating, I get this message:
![error png](https://user-images.githubusercontent.com/54072354/120494971-e2e83b80-c381-11eb-91c5-777d7b32a24a.png)

**Comment by Th3Whit3Wolf** [comment]
Update neovim and see if the errors persist. A new commit landed in neovim nightly changing the global option to `vim.go` from `vim.g`

**Comment by DannyDies** [comment]
In my case, this solved the problem. p.s. be aware of t_Co option, if you have if. it must be `vim.go.t_Co` too.

**Comment by pianocomposer321** [comment]
> Update neovim and see if the errors persist. A new commit landed in neovim nightly changing the global option to `vim.go` from `vim.g`

Just updated, it does fix it.
I wish the neovim people would just update the AUR repo already.
