### ISSUE TITLE
Rust with treesitter looks too red

### ISSUE THREAD

**Issue by polachok** [Th3Whit3Wolf/one-nvim#15]
I'm using neovim-0.5.0+ubuntu2+git202106062340-f2906a466-d569569c9 with nvim-treesitter (latest)

Currently structs in rust look like this:
![current-tree](https://user-images.githubusercontent.com/94035/121162990-17169d00-c857-11eb-9970-bdc7cf2b2c51.png)

Here's how it looks after I changed TSField from Identifier to Normal:
![after](https://user-images.githubusercontent.com/94035/121163010-1aaa2400-c857-11eb-8e73-b75db4f59846.png)

In your screenshot fields look more like mine, would you consider changing it?

**Comment by Th3Whit3Wolf** [comment]
Yeah send a pull request
