### ISSUE TITLE
C with treesitter looks werid

### ISSUE THREAD

**Issue by cvuuhk** [Th3Whit3Wolf/one-nvim#18]
I'm using neovim 0.5.0-1 on ArchLinux with nvim-treesitter (latest).
When I was editting a C file, the background of the macro is werid and I cannot recognize what the value it is clearly.
![20210804120834](https://user-images.githubusercontent.com/36870468/128121829-a4d978ea-ccee-408f-9389-4485ac6d4c5e.png)

And when I was coding just not finished, lsp-diagnosis will display like this: 
![20210804120843](https://user-images.githubusercontent.com/36870468/128122116-fb1fbf4e-0385-43b5-9b70-e4061562b5aa.png)

I don't know how to deal with it, would you consider changing it?
Thank you.

**Comment by xeluxee** [comment]
Try this workaround:
`hi TSError gui=none guifg=none guibg=none`

**Comment by cvuuhk** [comment]
> Try this workaround:
> `hi TSError gui=none guifg=none guibg=none`

It works, thank you.
