### ISSUE TITLE
Color cannot be overwritten

### ISSUE THREAD

**Issue by ya2s** [Th3Whit3Wolf/one-nvim#2]
If want to change the color of a particular highlight group, can't overwrite it in the usual way.
For example, it cannot be changed by the following method
```
highlight! ALEErrorSign guifg=#E06C75
```
Onebuddy could change this way.

If want to do the same with one-nvim, have to do the following
```
autocmd Colorscheme * highlight ALEErrorSign guifg=#E06C75
```

Can fix it?

**Comment by Th3Whit3Wolf** [comment]
Does it change when you run

```
highlight ALEErrorSign guifg=#E06C75
```

highlight! is not a command, I think you're confusing it with hi!

**Comment by rnevius** [comment]
`highlight!` is definitely a command (see `:help highlight-link`), but I'm not sure if it's only available when linking.

**Comment by ya2s** [comment]
> Does it change when you run

After the plugin is loaded, it will change if run it with vim running.
However, until now, it was described and set in init.lua and it worked, but it does not work with one-nvim.
Works well with plugins for other color schemes.

**Comment by Th3Whit3Wolf** [comment]
Are you calling it after setting the colorscheme?

**Comment by ya2s** [comment]
> Are you calling it after setting the colorscheme?

Yes, give it a try

**Comment by Th3Whit3Wolf** [comment]
I add 

```lua
vim.api.nvim_command('autocmd Colorscheme * highlight Normal guibg=#FF0000')
```

to the end of my `init.lua` and it worked. Try adding your autocmd to the last line of you `init.lua`.

**Comment by ya2s** [comment]
Yes i know.
I want to change it without using autocmd.
That's possible with onebuddy and other plugins

**Comment by Th3Whit3Wolf** [comment]
Sorry I misunderstood,

inside `nvim/after/colors/one-nvim.vim`

```vim
highlight ALEErrorSign guifg=#E06C75
```

where nvim is the root directory of your nvim folder.

**Comment by ya2s** [comment]
> Sorry I misunderstood,

I'm sorry in poor English😅

> nvim/after/colors/one-nvim.vim

I tried with this path and all the other syntax broke

**Comment by Th3Whit3Wolf** [comment]
Just to verify, if you are on linux,  if you run

```shell
cat ~/.config/nvim/after/colors/one-nvim.vim
```

you get 

```shell
highlight ALEErrorSign guifg=#E06C75
```

Is that right?

**Comment by ya2s** [comment]
Initial state
<img width="1186" alt="Screen Shot 2021-01-27 at 0 32 30" src="https://user-images.githubusercontent.com/42740055/105866956-e10b1600-6037-11eb-94a2-ab13cd6b3a53.png">

After setting
```
❯ cat ~/.config/nvim/after/colors/one-nvim.vim
highlight ALEErrorSign guifg=#E06C75
```
<img width="1186" alt="Screen Shot 2021-01-27 at 0 37 35" src="https://user-images.githubusercontent.com/42740055/105867105-08fa7980-6038-11eb-8396-f4607c6b4c84.png">

reference:
https://github.com/yamatsum/mackup/tree/master/.config/nvim

**Comment by Th3Whit3Wolf** [comment]
I think I have it now

```vim
" ~/.config/nvim/after/colors/one-nvim.vim
highlight ALEErrorSign guifg=#E06C75
```

```lua
-- end of init.lua
vim.api.nvim_command("runtime! after/colors/one-nvim.vim")
```

**Comment by ya2s** [comment]
After all it did not work.
Thank you for your kind answer.

The original purpose was just to overwrite the highlights with a simple setup.
Why can't one-nvim do what onebuddy can do?🤔

**Comment by Th3Whit3Wolf** [comment]
That's strange. It worked on my computer.

I think you're probably best off using the autocmd since you said that worked.
I have no idea why it would work with onebuddy but not one-nvim.

**Comment by Th3Whit3Wolf** [comment]
Worked this out with the creator of  [nvim-highlite](https://github.com/Iron-E/nvim-highlite)

```lua
vim.api.nvim_command("augroup Highlight")
vim.api.nvim_command("autocmd!")
vim.api.nvim_command("autocmd ColorScheme one-nvim hi! Normal guifg=#000000 guibg=#FFFFFF")
vim.api.nvim_command("augroup end")
vim.api.nvim_command("colorscheme one-nvim")
```

**Comment by Th3Whit3Wolf** [comment]
Or you could do

```lua
local vim, api, cmd = vim, vim.api, vim.cmd

local function augroups(definitions)
    for group_name, definition in pairs(definitions) do
        api.nvim_command("augroup " .. group_name)
        api.nvim_command("autocmd!")
        for _, def in ipairs(definition) do
            local command = table.concat(vim.tbl_flatten {"autocmd", def}, " ")
            api.nvim_command(command)
        end
        api.nvim_command("augroup END")
    end
end

local autocmds = {
    Highlight = {
        {"ColorScheme", "one-nvim", "hi! Normal guifg=#000000 guibg=#FFFFFF"}
    }
}

augroups(autocmds)
cmd 'colorscheme one-nvim'
```

It will do the same thing.

**Comment by ya2s** [comment]
I know I can change it with autocmd but I don't want to use autocmd just to overwrite colors.
This ticket will be closed so that I can proceed with the investigation.
Thank you.
