### ISSUE TITLE
Add Neovim 0.5.x LSP highlights

### ISSUE THREAD

**Issue by rnevius** [Th3Whit3Wolf/one-nvim#3]
Not an issue as much as a feature request. Neovim 0.5.0 will include a built-in LSP client. This client defines some highlights, viewable at `:help lsp-highlight`. These may include the following for `references`:

```
LspReferenceText
LspReferenceRead
LspReferenceWrite
```

And the following for `diagnostics`, which are all in the form of `LspDiagnostics<Something>` with `Error`, `Warning`, `Information` and `Hint` variants:

```
LspDiagnosticsDefaultError
LspDiagnosticsDefaultWarning
LspDiagnosticsDefaultInformation
LspDiagnosticsDefaultHint
LspDiagnosticsVirtualTextError
LspDiagnosticsVirtualTextWarning
LspDiagnosticsVirtualTextInformation
LspDiagnosticsVirtualTextHint
LspDiagnosticsUnderlineError
LspDiagnosticsUnderlineWarning
LspDiagnosticsUnderlineInformation
LspDiagnosticsUnderlineHint
LspDiagnosticsFloatingError
LspDiagnosticsFloatingWarning
LspDiagnosticsFloatingInformation
LspDiagnosticsFloatingHint
LspDiagnosticsSignError
LspDiagnosticsSignWarning
LspDiagnosticsSignInformation
LspDiagnosticsSignHint
```

Thanks for the beautiful theme!

**Comment by Th3Whit3Wolf** [comment]
Thanks for the issue! I just updated the theme with all of these set.

**Comment by onsails** [comment]
@Th3Whit3Wolf thanks for the update!
However theme still lacks LspReferenceText, LspReferenceRead and LspReferenceWrite which are crucial for working with rust sources.

I find the following highlights good enough for one-nvim dark:
```
  highlight LspReferenceText gui=reverse cterm=reverse
  highlight LspReferenceRead gui=reverse cterm=reverse
  " hue_6_2
  highlight LspReferenceWrite guibg=#e5c07b guifg=Black
```

**Comment by Th3Whit3Wolf** [comment]
Just updated. Let me know what you think.

**Comment by onsails** [comment]
Personally I prefer reference write to be more noticeable (bright bg):
<img width="163" alt="image" src="https://user-images.githubusercontent.com/107261/105870628-83f86b80-6009-11eb-9933-5fb045ef6be4.png">

Currently it's barely distinguisable from `mut` keyword and it's easy to miss state change:
<img width="178" alt="image" src="https://user-images.githubusercontent.com/107261/105870218-1b10f380-6009-11eb-9596-eca79c677ffb.png">

**Comment by Th3Whit3Wolf** [comment]
Just updated, the reverse tricked me. Let me know what you think.

**Comment by onsails** [comment]
perfect, thanks!

**Comment by Th3Whit3Wolf** [comment]
No problem!
