### ISSUE TITLE
zfs suggestions color

### ISSUE THREAD

**Issue by onsails** [Th3Whit3Wolf/one-nvim#6]
In terminal mode [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) dissapear.
How it should be:
<img width="51" alt="image" src="https://user-images.githubusercontent.com/107261/107637910-e98e5e00-6c7f-11eb-8a1d-9feea65661c4.png">

How it is:
<img width="42" alt="image" src="https://user-images.githubusercontent.com/107261/107638272-6588a600-6c80-11eb-946d-64915b602c2f.png">

It's a flaw of almost every vim theme, that's why I have the following in my config:
```vim
  let g:terminal_color_8=8
```
which makes suggestions look just like they look in my regular terminal.
Perhaps you would like to put the same (or a bit different) color setting into one-nvim.

**Comment by Th3Whit3Wolf** [comment]
Are you on the most recent commit?

This is what mine looks like.

![20210212_12h14m47s_grim](https://user-images.githubusercontent.com/48275422/107766933-26179380-6d2c-11eb-9230-445552aa26f9.png)

**Comment by onsails** [comment]
hmm, yes, I'm on 88916fbb81530a25f9a3f8bc02e1b4c91ff7be10
I've checked both Alacritty and iTerm.

**Comment by Th3Whit3Wolf** [comment]
That's weird, I use alacritty. I'll try to see what's going on

**Comment by onsails** [comment]
I've created a minimal repro: https://github.com/onsails/nvim-reproduce-zsh-suggestions

**Comment by Th3Whit3Wolf** [comment]
This issue should be solved but please update to the latest commit in verify when you get the chance.
