### ISSUE TITLE
IncSearch highlight is hard to see

### ISSUE THREAD

**Issue by rnevius** [Th3Whit3Wolf/one-nvim#7]
The `IncSearch` highlight should probably have a background to distinguish matches better. This background could ideally be a completely different color (or even just a slightly different hue) than the `Search` highlight.

The issue can be seen when matching `Number`s, `Boolean`s, and more:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/4516305/110104213-27763200-7da7-11eb-8955-11a8cb487927.png">

As you can see, the matched line is highlighted differently, but the matched text is not during incsearch (because the `IncSearch` highlight matches these other highlight groups). When `<CR>` is pressed, the match is highlighted more clearly by the `Search` highlight:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/4516305/110104379-60160b80-7da7-11eb-82a1-c5fe97f843cc.png">

This gets even more confusing when there are other incsearch matches in the buffer, because everything _except_ for the first match is highlighted clearly during the search.

**Comment by Th3Whit3Wolf** [comment]
This colorscheme is pretty much a lua port of [rakr/vim-one](https://github.com/rakr/vim-one) which is were this behavior comes from. [joshdick/onedark.vim](https://github.com/joshdick/onedark.vim) sets the `IncSearch` background to the same as the comments. How does IncSearch look when you set the background color to `#a0a1a7`?

**Comment by rnevius** [comment]
> This colorscheme is pretty much a lua port of rakr/vim-one which is were this behavior comes from

I moved to [Th3Whit3Wolf/one-nvim](https://github.com/Th3Whit3Wolf/one-nvim) from [rakr/vim-one](https://github.com/rakr/vim-one), and the latter definitely doesn't have this issue. Here's what happens when I do the same search as in the original issue, while using `vim-one`:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/4516305/110320016-f8aec480-800f-11eb-9483-b863f144c380.png">

As expected, the search result is clearly incrementally highlighted.

More specifically, the highlight groups for `Search` and `IncSearch` are as follows when using the light background variant:

| | Th3Whit3Wolf/one-nvim | rakr/vim-one |
|---|---|---|
| `Search` | ctermbg=11 guifg=#fafafa guibg=#c18401 | ctermfg=255 ctermbg=136 guifg=#fafafa guibg=#c18401 |
|`IncSearch` | cterm=reverse guifg=#986801 | cterm=reverse ctermfg=94 gui=reverse guifg=#986801 |

The same issue also appears in the dark background version.

**Comment by Th3Whit3Wolf** [comment]
That's weird. They define IncSearch [here](https://github.com/rakr/vim-one/blob/187f5c85b682c1933f8780d4d419c55d26a82e24/colors/one.vim#L370) as 

```viml
  call <sid>X('IncSearch',    s:hue_6,         '',               '')
```

**Comment by Th3Whit3Wolf** [comment]
Neither should be setting reverse style for cterm or gui. It looks like your cterm colors aren't being set correctly either based on your table.

**Comment by Th3Whit3Wolf** [comment]
When you get an opportunity update one-nvim and let me know what you think about the changes to `IncSearch` background

**Comment by rnevius** [comment]
Thanks @Th3Whit3Wolf much better!

Regarding your comment about my cterm colors, I'm using [kitty](https://github.com/kovidgoyal/kitty) as my terminal emulator. Is it possible that these colors are being overridden by kitty? I'm not sure it really matters in my case, but I'd be interested in knowing what could cause something like that.

**Comment by Th3Whit3Wolf** [comment]
To my knowledge the terminal should not be able to affect variables inside of neovim other than environment variables. I would guess that another plugin is modifying IncSearch and Search but I'm not sure.

**Comment by Th3Whit3Wolf** [comment]
Also have you set termguicolors?

**Comment by rnevius** [comment]
Yes, `'termguicolors'` is set.

**Comment by Th3Whit3Wolf** [comment]
It looks like something set reverse style for `cterm` and `gui` on rakr/vim-one and only `cterm` on one-nvim. Since `termguicolors` is set the `cterm` value is ignored.
