### ISSUE TITLE
last commit has changed the normal background color

### ISSUE THREAD

**Issue by ya2s** [Th3Whit3Wolf/one-nvim#8]
https://github.com/Th3Whit3Wolf/one-nvim/commit/8767c8e2d5aa1d270252528b167f0eb0911bb77a
This commit has changed the normal background color(`syntax_bg`).
Is this an intended change?

This color is no longer one-dark
https://github.com/atom/atom/tree/master/packages/one-dark-syntax
https://github.com/joshdick/onedark.vim

**Comment by ya2s** [comment]
https://github.com/Th3Whit3Wolf/one-nvim/commit/8767c8e2d5aa1d270252528b167f0eb0911bb77a#diff-c5275e2249049c055ced584c121ac0286dacfbfd26eb2c452b135f51937c745bR39-R41
I don't think it's good to add special color away from one-dark like this.
Or "one" should not be used in the name.

**Comment by Th3Whit3Wolf** [comment]
Sorry about that, should be fixed now.
